export default [
  {
    id: 1,
    reasonBy: `<strong>MATHIAS OKE,</strong> TORONTO, ON`,
    reasonBigHeading: `A Drive-in in the Way`,
    reasonDescription: `<p><strong>Sometimes, if we’re good and for special nights, my mom and dad let us watch movies in the back of our van.</strong> They make us popcorn, we put on our pajamas, and have blankets, and they let us stay in there with juice. We don’t even have to put on our seatbelts, because we’re not going anywhere. Sometimes, we even have my friends over, we sit in the chairs or sit on the floor, and wear our headphones. And sometimes, we fall asleep. But it’s still fun.</p>`,
    reasonDescriptionTablet: `<p><strong>Sometimes, if we’re good and for special nights, my mom and dad let us watch movies in the back of our van.</strong> They make us popcorn, we put on our pajamas, and have blankets, and they let us stay in there with juice. We don’t even have to put on our seatbelts, because we’re not going anywhere. Sometimes, we even have my friends over, we sit in the chairs or sit on the floor, and wear our headphones. And sometimes, we fall asleep. But it’s still fun.</p>`,
    reasonGridTitle: `We can keep everyone warm and happy in our Sienna.`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>An <strong>available rear entertainment system includes an 11.6-inch video screen that pulls down from the ceiling,</strong> along with an <strong>HDMI port and two wireless headphones.</strong> Passengers in the third row can also use a headphone jack.</p>`,
    blockSize: `s`,
  },
  {
    id: 2,
    reasonBy: `<strong>JENN,</strong> MONTREAL, QC`,
    reasonBigHeading: `The Security Blanket`,
    reasonDescription: `<p>Our old van didn’t have all the fancy safety gadgets that newer vehicles do, and we didn’t really think anything of it. But then my husband got a newer car a couple years ago with features such as emergency braking and blind spot warning, and we both knew our next van needed this when we upgraded last year. <strong>We’ve never had to use these features, but it’s nice to know that they’re just another layer of safety for us.</strong> Of course, it’s my family; we’ll do anything that makes our drive safer.</p>`,
    reasonDescriptionTablet: `<p>Our old van didn’t have all the fancy safety gadgets that newer vehicles do, and we didn’t really think anything of it. But then my husband got a newer car a couple years ago with features such as emergency braking and blind spot warning, and we both knew our next van needed this when we upgraded last year. <strong>We’ve never had to use these features, but it’s nice to know that they’re just another layer of safety for us.</strong> Of course, it’s my family; we’ll do anything that makes our drive safer.</p>`,
    reasonGridTitle: `We can keep everyone warm and happy in our Sienna.`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>Every Sienna is equipped with <strong>Toyota Safety Sense™ 2.0,</strong> a suite of advanced safety features that includes Pre-Collision System with Pedestrian Detection/Low Light Detection and Bicycle Detection, Full-Speed Range Dynamic Radar Cruise Control, Lane Departure Alert with Lane Trace Assist and Automatic High Beams. Also standard is Blind Spot Monitor with Rear Cross Traffic Alert. </p>`,
    blockSize: `l`,
  },
  {
    id: 3,
    reasonBy: `<strong>THOMAS,</strong> KELOWNA, BC`,
    reasonBigHeading: `A Concert on the Go`,
    reasonDescription: `<p>We bought a minivan mainly for the family, but I’m also on the road a lot with my sales job, and I like the added room for my samples. But I also appreciate the alone time, too. <strong>For one thing, it’s great I can pair my phone with Bluetooth and take calls on the road. But I also like to just play the music I want, instead of what the kids want.</strong> I can be a picky audiophile, and the satellite radio helps keep me tuned in to my favourites.</p>`,
    reasonDescriptionTablet: `<p>We bought a minivan mainly for the family, but I’m also on the road a lot with my sales job, and I like the added room for my samples. But I also appreciate the alone time, too. <strong>For one thing, it’s great I can pair my phone with Bluetooth and take calls on the road. But I also like to just play the music I want, instead of what the kids want.</strong> I can be a picky audiophile, and the satellite radio helps keep me tuned in to my favourites.</p>`,
    reasonGridTitle: `We can keep everyone warm and happy in our Sienna.`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>Every Sienna gets a <strong>9-inch touchscreen with Apple CarPlay™ and Android Auto™, Bluetooth and seven USB charging ports.</strong> Available is a 12-speaker JBL® Premium Audio with a subwoofer and 1,200-watt amplifier, plus Clari-Fi® digital restoration technology. Sirius satellite radio is also available and comes with a 3-month, all-access trial subscription.</p>`,
    blockSize: `l`,
  },
  {
    id: 4,
    reasonBy: `<strong>MILA RICHARD DALCOURT,</strong> MONTREAL, PQ`,
    reasonBigHeading: `A Finding Calm in the Rear Seats`,
    reasonDescription: `<p>I have been doing ballet for a few years now, and I really like it. My brother plays hockey, and my sister is in figure skating. So my moms are always taking us out for these, on nights and weekends. <strong>We get into the back seats and buckle up, but my brother can bother me sometimes, so I put on the headphones and listen to the music I’ll be dancing to.</strong> It lets me get calm for when we get there.</p>`,
    reasonDescriptionTablet: `<p>I have been doing ballet for a few years now, and I really like it. My brother plays hockey, and my sister is in figure skating. So my moms are always taking us out for these, on nights and weekends. <strong>We get into the back seats and buckle up, but my brother can bother me sometimes, so I put on the headphones and listen to the music I’ll be dancing to.</strong> It lets me get calm for when we get there.</p>`,
    reasonGridTitle: `We can keep everyone warm and happy in our Sienna.`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>An <strong>available rear entertainment</strong> system includes an 11.6-inch video screen that pulls down from the ceiling, along with an HDMI port and two wireless headphones. Passengers in the third row can also use a headphone jack.</p>`,
    blockSize: `s`,
  },
  {
    id: 5,
    reasonBy: `<strong>RICK,</strong> SASKATOON`,
    reasonBigHeading: `A Penny-Pincher at the Pumps`,
    reasonDescription: `<p>I like to think I’m frugal; my children might call me cheap. But I like to try and save as much on gas as possible, much to the annoyance of my family. <strong>Luckily, our van gets great fuel economy, it’s one of the reasons we bought it.</strong> But I’ve still got little tricks to make it better, such as keeping it to the speed limit, using a tint on the windows so we don’t use the A/C as much in the summer, and never idling the engine while I’m waiting for someone. I guess saving my money at the pumps is my hobby.</p>`,
    reasonDescriptionTablet: `<p>I like to think I’m frugal; my children might call me cheap. But I like to try and save as much on gas as possible, much to the annoyance of my family. <strong>Luckily, our van gets great fuel economy, it’s one of the reasons we bought it.</strong> But I’ve still got little tricks to make it better, such as keeping it to the speed limit, using a tint on the windows so we don’t use the A/C as much in the summer, and never idling the engine while I’m waiting for someone. I guess saving my money at the pumps is my hobby.</p>`,
    reasonGridTitle: `We can keep everyone warm and happy in our Sienna.`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>With the Sienna, there’s no need for extreme measures to save fuel. Every model is a hybrid, with a 2.5L four cylinder engine combined with either two electric motors for the front-drive system, or three with the all-wheel-drive versions. <strong>The Sienna is rated at 6.6L/100 km in the city, 6.5L/100km highway and a combined 6.5L/100km.</strong> That’s better fuel economy than many compact hatchbacks.</p>`,
    blockSize: `s`,
  },
  {
    id: 6,
    reasonBy: `<strong>ALEXANDRIA,</strong> ON`,
    reasonBigHeading: `A Helping Kick`,
    reasonDescription: `<p>My husband and I run two restaurants business, and the van is instrumental to how we transport product between locations. <strong>We like that it has an automatic opening rear hatch, with just a wave of a foot underneath the bumper.</strong> When you’re carrying 50-pound crates of food and bottles back and forth, a little extra help is always appreciated.</p>`,
    reasonDescriptionTablet: `<p>My husband and I run two restaurants business, and the van is instrumental to how we transport product between locations. <strong>We like that it has an automatic opening rear hatch, with just a wave of a foot underneath the bumper.</strong> When you’re carrying 50-pound crates of food and bottles back and forth, a little extra help is always appreciated.</p>`,
    reasonGridTitle: `It is so comfortable`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>The Sienna offers <strong>available power sliding doors with kick sensor and power rear door with kick sensor.</strong> The kick sensor convenience allows hands-free operation with the key fob in your pocket.</p>`,
    blockSize: `l`,
  },
  {
    id: 7,
    reasonBy: `<strong>TIMOTHY,</strong> FORT MCMURRAY, AB`,
    reasonBigHeading: `Saving the World`,
    reasonDescription: `<p>My partner and I are firefighters in Fort McMurray, Alberta. In last year’s wildfire rescue efforts we were finding that animal rescue operation was being stretched, so I borrowed my brother’s Sienna and converted it into a rescue van. Took seats out, placed a wood board to flatten surface, topped with two comforters, added a layer of heating pads connected to extra AC outlets in the center console and another one to the 120V DC outlet from the rear. Topped it with another comforter and, bam: comfy animal bed. <strong>Saved this family and a few more – 93 animal friends saved overall!</strong></p>`,
    reasonDescriptionTablet: `<p>My partner and I are firefighters in Fort McMurray, Alberta. In last year’s wildfire rescue efforts we were finding that animal rescue operation was being stretched, so I borrowed my brother’s Sienna and converted it into a rescue van. Took seats out, placed a wood board to flatten surface, topped with two comforters, added a layer of heating pads connected to extra AC outlets in the center console and another one to the 120V DC outlet from the rear. Topped it with another comforter and, bam: comfy animal bed. <strong>Saved this family and a few more – 93 animal friends saved overall!</strong></p>`,
    reasonGridTitle: `We can keep everyone warm and happy in our Sienna.`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p><strong>Available on the Sienna is a 1500W inverter, enough to power kitchen appliances, power tools or other electrical devices.</strong> Two 120V outlets are located inside; one on the back of the front console, and one in the rear cargo area.</p>`,
    blockSize: `l`,
  },
  {
    id: 8,
    reasonBy: `<strong>JILL,</strong> ST. JOHN, NB`,
    reasonBigHeading: `Connections for Everyone`,
    reasonDescription: `<p>When do you have too many electronic devices? I think our family does; all five of us each have a phone, and the three boys have tablets. And when we’re in the van, how do we all charge with just two USB ports? <strong>I’ve decided to keep a portable charger in the centre console, charging when we’re not driving,</strong> so at least they can share a couple more ports for the inevitable ‘low battery’ when they need it.</p>`,
    reasonDescriptionTablet: `<p>When do you have too many electronic devices? I think our family does; all five of us each have a phone, and the three boys have tablets. And when we’re in the van, how do we all charge with just two USB ports? <strong>I’ve decided to keep a portable charger in the centre console, charging when we’re not driving,</strong> so at least they can share a couple more ports for the inevitable ‘low battery’ when they need it.</p>`,
    reasonGridTitle: `I can do so many things`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>Every Sienna comes standard with no less than <strong>seven USB charging ports, (both USB-A and USB-C)</strong> throughout the cabin. One port in the dash also serves to connect a phone with the infotainment system. An available Qi wireless phone charging tray is also located in the front dash.</p>`,
    blockSize: `s`,
  },
  {
    id: 9,
    reasonBy: `<strong>ERICA,</strong> HALIFAX, NS`,
    reasonBigHeading: `Throwing Shade`,
    reasonDescription: `<p>Each year we take a vacation with our van; a trip out west to Montreal or Toronto, or sometimes to a rented cottage in New Brunswick or P.E.I. And having the room that a van provides, for both people and our luggage, honestly just adds to the trip. But keeping our two boys calm during the trip takes some planning and work; neither of them are the best travellers. <strong>So we actually use parchment paper on the rear windows to limit the bright sun and keep the interior cooler.</strong> And honestly, it keeps everyone cooler in more ways than one.</p>`,
    reasonDescriptionTablet: `<p>Each year we take a vacation with our van; a trip out west to Montreal or Toronto, or sometimes to a rented cottage in New Brunswick or P.E.I. And having the room that a van provides, for both people and our luggage, honestly just adds to the trip. But keeping our two boys calm during the trip takes some planning and work; neither of them are the best travellers. <strong>So we actually use parchment paper on the rear windows to limit the bright sun and keep the interior cooler.</strong> And honestly, it keeps everyone cooler in more ways than one.</p>`,
    reasonGridTitle: `I can do so many things`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>You don’t need parchment paper to make the trip more serene for a rest. Every Sienna comes with <strong>2nd Row Sunshade on Sliding Doors</strong> that roll up out of the doors to help block sunlight and keep the interior cooler. Also available are 3rd Sunshades on Quarter Windows.</p>`,
    blockSize: `s`,
  },
  {
    id: 10,
    reasonBy: `<strong>MICHAEL GARCIA,</strong> TORONTO, ON`,
    reasonBigHeading: `A Portable Studio`,
    reasonDescription: `<p>We bought a van for our growing family, but for me as a musician, it’s had unexpected benefits, too. For one thing, I can fit all of my stuff in it for shows, so no more renting trucks. Even if I don’t have a show, I still have to practise. But with a four-year-old and 17-month-old, I can’t start playing after bedtime. <strong>So that’s where my van turns into a private studio, where I bring my instruments in and close the doors for some alone time, without disturbing anyone.</strong> Honestly, I don’t know how we survived without a van before this.</p>`,
    reasonDescriptionTablet: `<p>We bought a van for our growing family, but for me as a musician, it’s had unexpected benefits, too. For one thing, I can fit all of my stuff in it for shows, so no more renting trucks. Even if I don’t have a show, I still have to practise. But with a four-year-old and 17-month-old, I can’t start playing after bedtime. <strong>So that’s where my van turns into a private studio, where I bring my instruments in and close the doors for some alone time, without disturbing anyone.</strong> Honestly, I don’t know how we survived without a van before this.</p>`,
    reasonGridTitle: `We can keep everyone warm and happy in our Sienna.`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>With all rear seats folded to the front, the Sienna has a full <strong>2,860L of flat-floor cargo space.</strong> Even with the second-row in place, there is still a generous 2,129L, while behind the third row is 949L, good for a full set of luggage.</p>`,
    blockSize: `l`,
  },
  {
    id: 11,
    reasonBy: `<strong>ELAINE,</strong> NORTH BAY, ON`,
    reasonBigHeading: `Warmth in Cold Times`,
    reasonDescription: `<p>OK, I’ll admit, I’m a wimp when it comes to winter. And I live in a northern city, too! So, when it comes to those cold mornings, I need everything heated in my vehicle. I don’t like scraping, I don’t like that icy steering wheel and, even worse, the icy seat. <strong>So my van is loaded with everything to help defeat winter, such as heated seats, heated mirrors and, my favourite, remote start</strong> – so I can get everything defrosted before I even leave the door every morning.</p>`,
    reasonDescriptionTablet: `<p>OK, I’ll admit, I’m a wimp when it comes to winter. And I live in a northern city, too! So, when it comes to those cold mornings, I need everything heated in my vehicle. I don’t like scraping, I don’t like that icy steering wheel and, even worse, the icy seat. <strong>So my van is loaded with everything to help defeat winter, such as heated seats, heated mirrors and, my favourite, remote start</strong> – so I can get everything defrosted before I even leave the door every morning.</p>`,
    reasonGridTitle: `It is so comfortable`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p><strong>Every Sienna model is ready for Canadian winters,</strong> with standard features that include heated front seats, a heated steering wheel, heated exterior mirrors, windshield wiper de-icer and rear-window defroster. The Limited version also gets heated second-row seats.</p>`,
    blockSize: `l`,
  },
  {
    id: 12,
    reasonBy: `<strong>DEBORAH,</strong> QUEBEC CITY`,
    reasonBigHeading: `Comfort for Everyone`,
    reasonDescription: `<p>We all love long road trips. <strong>The rear rows are especially good for those passengers, who like to curl up in the seats and either read, snooze or listen to music while watching the scenery go by.</strong> Especially in the winter, they love to snuggle up and get cozy with a warm blanket; that usually means they’ll be asleep in no time. Blankets are also handy for us to keep the cabin cooler for those who don’t want to get too warm with the cabin heater. That way, everyone stays comfortable!</p>`,
    reasonDescriptionTablet: `<p>We all love long road trips. <strong>The rear rows are especially good for those passengers, who like to curl up in the seats and either read, snooze or listen to music while watching the scenery go by.</strong> Especially in the winter, they love to snuggle up and get cozy with a warm blanket; that usually means they’ll be asleep in no time. Blankets are also handy for us to keep the cabin cooler for those who don’t want to get too warm with the cabin heater. That way, everyone stays comfortable!</p>`,
    reasonGridTitle: `We can keep everyone warm and happy in our Sienna.`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>The base Sienna LE has <strong>three-zone climate control that allows separate temperatures to be set for each row.</strong> But step up to the XLE and higher and the four-zone climate control will have second- and third-row temperature regulation along with separate controls for the driver and front passenger.</p>`,
    blockSize: `s`,
  },
  {
    id: 13,
    reasonBy: `<strong>DAVID,</strong> TIMMINS, ON`,
    reasonBigHeading: `Eyes Front & Rear`,
    reasonDescription: `<p>My dad taught me a trick a long time ago that would end up saving my van a lot of scrapes and dings: tether a rubber ball from a string in your garage, just where the windshield sits when parked perfectly. That way, you know exactly when to stop when you’re parking inside. Of course, that doesn’t take into account when the kids leave their bikes or garbage cans where they shouldn’t be. <strong>That’s why I love the parking sensors in my new van; not only does it help in the garage, but in tight parking lots too.</strong></p>`,
    reasonDescriptionTablet: `<p>My dad taught me a trick a long time ago that would end up saving my van a lot of scrapes and dings: tether a rubber ball from a string in your garage, just where the windshield sits when parked perfectly. That way, you know exactly when to stop when you’re parking inside. Of course, that doesn’t take into account when the kids leave their bikes or garbage cans where they shouldn’t be. <strong>That’s why I love the parking sensors in my new van; not only does it help in the garage, but in tight parking lots too.</strong></p>`,
    reasonGridTitle: `We can keep everyone warm and happy in our Sienna.`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p><strong>Available front and rear parking sensors</strong> ensure safe positioning of the Sienna every time.</p>`,
    blockSize: `s`,
  },
  {
    id: 14,
    reasonBy: `<strong>MARYANNE,</strong> SALMON ARM, BC`,
    reasonBigHeading: `A Place for Everything`,
    reasonDescription: `<p>Having a van gives you a lot of room, but sometimes, it could be a bit much. If I just have my purse with me, I don’t need to have it wailing about in the back when I drive. But if I have a passenger, I can’t exactly put it on the seat beside me. But, aha! <strong>My van has a storage compartment that takes my purse, right between the front seats.</strong> Now I know where it is and it doesn't spill all over the place when I drive.</p>`,
    reasonDescriptionTablet: `<p>Having a van gives you a lot of room, but sometimes, it could be a bit much. If I just have my purse with me, I don’t need to have it wailing about in the back when I drive. But if I have a passenger, I can’t exactly put it on the seat beside me. But, aha! <strong>My van has a storage compartment that takes my purse, right between the front seats.</strong> Now I know where it is and it doesn't spill all over the place when I drive.</p>`,
    reasonGridTitle: `It is so comfortable`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>Every Sienna has a <strong>generous-size centre console storage compartment, but bags and other larger items have their own place,</strong> under the Bridge Console that houses the gear shifter. A large and convenient area with a light right between the front seats is the perfect place for your bag.</p>`,
    blockSize: `l`,
  },
  {
    id: 15,
    reasonBy: `<strong>DARLA,</strong> EDMONTON, AB`,
    reasonBigHeading: `All In-Van Drive-In`,
    reasonDescription: `<p>Our family is crazy for road trips! Which is good, because grandma lives down the highway in Calgary, and we have some cousins in Vancouver we like to see sometimes. And while the pre-teens are keen to go, they also need a bit of entertainment sometimes, if not for anything else but to stay out of mom and dad’s hair. We had to get them each an iPad they use for movies, games or music, and that keeps them pretty occupied until we finally get to our destination. <strong>They spend almost the whole trip watching movies and, more importantly, staying quiet.</strong></p>`,
    reasonDescriptionTablet: `<p>Our family is crazy for road trips! Which is good, because grandma lives down the highway in Calgary, and we have some cousins in Vancouver we like to see sometimes. And while the pre-teens are keen to go, they also need a bit of entertainment sometimes, if not for anything else but to stay out of mom and dad’s hair. We had to get them each an iPad they use for movies, games or music, and that keeps them pretty occupied until we finally get to our destination. <strong>They spend almost the whole trip watching movies and, more importantly, staying quiet.</strong></p>`,
    reasonGridTitle: `I can do so many things`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>Available on the XSE and standard on the Limited is the <strong>rear entertainment system, which includes an 11.6-inch video screen</strong> that pulls down from the ceiling, along with an HDMI port and two wireless headphones. Passengers in the third row can also use a headphone jack.</p>`,
    blockSize: `l`,
  },
  {
    id: 16,
    reasonBy: `<strong>SONIA,</strong> WINNIPEG, MB`,
    reasonBigHeading: `Technology Keeps the Way Clear`,
    reasonDescription: `<p>A van comes in very handy for my hobby of refinishing and selling old furniture. It seems just about anything fits in there with the seats down when I’m delivering to clients or picking up new work. But when I’ve got things stacked up back there, there’s no way I can use a regular rearview mirror. <strong>Thankfully, this mirror is the Digital Display Rearview Mirror; it feeds off the backup camera so I can see everything behind me.</strong> It’s just so much peace of mind, and certainly safer.</p>`,
    reasonDescriptionTablet: `<p>A van comes in very handy for my hobby of refinishing and selling old furniture. It seems just about anything fits in there with the seats down when I’m delivering to clients or picking up new work. But when I’ve got things stacked up back there, there’s no way I can use a regular rearview mirror. <strong>Thankfully, this mirror is the Digital Display Rearview Mirror; it feeds off the backup camera so I can see everything behind me.</strong> It’s just so much peace of mind, and certainly safer.</p>`,
    reasonGridTitle: `We can keep everyone warm and happy in our Sienna.`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>Available on the XSE and standard with the Limited, the <strong>Digital Display Rearview Mirror</strong> may look like an ordinary mirror at first. But when your rear sight is impeded by passengers or cargo, flip it up and it turns into a digital screen, with the image feeding from the rear camera.</p>`,
    blockSize: `s`,
  },
  {
    id: 17,
    reasonBy: `<strong>GEOFF,</strong> ST. JOHN’S, NFLD`,
    reasonBigHeading: `A Bird’s Eye View for Safety`,
    reasonDescription: `<p>I wasn’t used to the size of my new van, after coming from a smaller car. It was a little intimidating, especially in parking lots. But then I discovered this feature I didn’t even know my van had: a 360-degree camera system that lets me see everything all around the vehicle when I’m slowly maneuvering, all through my infotainment screen. <strong>Now I don’t have to worry about dinging those shopping carts or scuffing my wheels on taller curbs anymore.</strong> Another plus: I’m so good at parking now, I make it look like I know what I’m doing!</p>`,
    reasonDescriptionTablet: `<p>I wasn’t used to the size of my new van, after coming from a smaller car. It was a little intimidating, especially in parking lots. But then I discovered this feature I didn’t even know my van had: a 360-degree camera system that lets me see everything all around the vehicle when I’m slowly maneuvering, all through my infotainment screen. <strong>Now I don’t have to worry about dinging those shopping carts or scuffing my wheels on taller curbs anymore.</strong> Another plus: I’m so good at parking now, I make it look like I know what I’m doing!</p>`,
    reasonGridTitle: `I can do so many things`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>Available on the Sienna is the Bird’s Eye View Cameras with Perimeter Scan. <strong>This feature lets you see every corner of the Sienna through the 9-inch touchscreen for perfect, safe parking.</strong> Curb View also helps avoid scuffing your wheels when parking near curbs, too.</p>`,
    blockSize: `s`,
  },
  {
    id: 18,
    reasonBy: `<strong>NOUR,</strong> HAMILTON, ON`,
    reasonBigHeading: `Taking Everything with You`,
    reasonDescription: `<p>My parents have always loved camping, but last year they decided it was enough, and gave us their small – but very cool – camp trailer. <strong>This has been a game-changer for us in the summer; no more setting up and folding tents, no more cooking under a tarp in the rain.</strong> We can now camp in style! And luckily, it’s just small enough for us to tow it behind our van. This old camper is now part of our life, and maybe someday we’ll pass it on to our kids – but not yet.</p>`,
    reasonDescriptionTablet: `<p>My parents have always loved camping, but last year they decided it was enough, and gave us their small – but very cool – camp trailer. <strong>This has been a game-changer for us in the summer; no more setting up and folding tents, no more cooking under a tarp in the rain.</strong> We can now camp in style! And luckily, it’s just small enough for us to tow it behind our van. This old camper is now part of our life, and maybe someday we’ll pass it on to our kids – but not yet.</p>`,
    reasonGridTitle: `We can keep everyone warm and happy in our Sienna.`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>Every Sienna, whether front-wheel drive or all-wheel drive, is equipped to <strong>tow up to 3,500 lbs safely with the available towing package,</strong> giving you options for your small trailer, boat or other equipment that accompanies your busy life.</p>`,
    blockSize: `l`,
  },
  {
    id: 19,
    reasonBy: `<strong>LAMAR,</strong> TORONTO, ON`,
    reasonBigHeading: `Limo-Like Legroom`,
    reasonDescription: `<p>I’m 6’4”, and my thing is basketball. I know, surprising. But I like to organize some neighbourhood ball on the weekends, so I offer to pick up a few guys, and they need space – lots of it. <strong>My van is a lot better option than their cars; it’s got the headroom we need, plus a bit of space to stretch out, and then room for a few balls and cases of water.</strong> They may like their fast cars, but they appreciate the van for not having their heads scrape the ceiling inside.</p>`,
    reasonDescriptionTablet: `<p>I’m 6’4”, and my thing is basketball. I know, surprising. But I like to organize some neighbourhood ball on the weekends, so I offer to pick up a few guys, and they need space – lots of it. <strong>My van is a lot better option than their cars; it’s got the headroom we need, plus a bit of space to stretch out, and then room for a few balls and cases of water.</strong> They may like their fast cars, but they appreciate the van for not having their heads scrape the ceiling inside.</p>`,
    reasonGridTitle: `It is so comfortable`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>The XSE and Limited versions of the Sienna have <strong>available 2nd row Long Slide Captains Chairs</strong> that open up incredible room for passengers. They both independently slide up to 63.5 centimetres, giving even tall people enough room to stretch out. The third row is also designed for adults to be comfortable, too, and not just children.</p>`,
    blockSize: `l`,
  },
  {
    id: 20,
    reasonBy: `<strong>THOMAS,</strong> KELOWNA, BC`,
    reasonBigHeading: `A Concert on the Go`,
    reasonDescription: `<p>We bought a minivan mainly for the family, but I’m also on the road a lot with my sales job, and I like the added room for my samples. But I also appreciate the alone time, too. For one thing, it’s great I can pair my phone with Bluetooth and take calls on the road. But I also like to just play the music I want, instead of what the kids want. <strong>I can be a picky audiophile, and the satellite radio helps keep me tuned in to my favourites.</strong></p>`,
    reasonDescriptionTablet: `<p>We bought a minivan mainly for the family, but I’m also on the road a lot with my sales job, and I like the added room for my samples. But I also appreciate the alone time, too. For one thing, it’s great I can pair my phone with Bluetooth and take calls on the road. But I also like to just play the music I want, instead of what the kids want. <strong>I can be a picky audiophile, and the satellite radio helps keep me tuned in to my favourites.</strong></p>`,
    reasonGridTitle: `We can keep everyone warm and happy in our Sienna.`,
    reviewBy: `NEIL VORANO`,
    reviewDescription: `<p>Every Sienna gets a <strong>9-inch touchscreen with Apple CarPlay™ and Android Auto™, Bluetooth and seven USB charging ports.</strong> Available is a 12-speaker JBL® Premium Audio with a subwoofer and 1,200-watt amplifier, plus Clari-Fi® digital restoration technology. Sirius satellite radio is also available and comes with a 3-month, all-access trial subscription.</p>`,
    blockSize: `s`,
  },
]
